### ISSUE TITLE
Compare when memory access become faster then calculation with recursion

### ISSUE THREAD

**Issue by Konard** [linksplatform/Numbers#44]
https://github.com/linksplatform/Numbers/blob/6fb7677ee0aec676b641b86f6c3aa08b02abc5c7/Platform.Numbers/Math.cs#L16-L22
https://github.com/linksplatform/Numbers/blob/6fb7677ee0aec676b641b86f6c3aa08b02abc5c7/Platform.Numbers/Math.cs#L36-L47

**Comment by Konard** [comment]
This also can be compared with loop-implementation with no recursion. All this benchmarks can be added as a project inside the solution.

**Comment by Ythosa** [comment]
A whole study was conducted! As a result, I can say that accessing memory is faster than any algorithm. It was also found that recursion is the most efficient algorithm in C#.

The tested algorithms are presented [here](https://github.com/linksplatform/Numbers/blob/master/csharp/Platform.Numbers/Math.cs#L44).

The benchmarks - (here)[https://github.com/linksplatform/Numbers/blob/master/csharp/Platform.Numbers.Benchmarks/MathBenchmarks.cs]

I also attach the comparison results.

P.S.: We also tested such algorithms as the tree calculation algorithm and the factorization calculation algorithm, but they are not given in the examples.

![mXiGYTeKJdA](https://user-images.githubusercontent.com/10869361/87246443-43167c00-c456-11ea-8c36-8c77b87479fc.jpg)
